### ISSUE TITLE
执行sdk的sm2方法案例报错

### ISSUE THREAD

**Issue by zxx12138going** [alipay/alipay-sdk-java-all#16]

**Comment by zxx12138going** [comment]
注意的是，依赖的最新版本4.9.106.ALL。目前我想使用sdk里面的sm2加密方法，我按照sdk提供的，执行Test案例中ExecuteTest 的方法：should_return_success_when_request_and_response_encrypted_sm2()方法，程序报错，部分报错日志如下 com.alipay.api.AlipayApiException: SM2签名遭遇异常，请检查私钥格式是否正确。null content=alipay_sdk=alipay-sdk-java-dynamicVersionNo&app_id=2021000146614327&charset=utf-8&format=json&method=alipay.open.operation.openbizmock.biz.query&sign_type=SM2&timestamp=2020-04-13 09:44:49&version=1.0，charset=utf-8，privateKeySize=184
	at com.alipay.api.DefaultSigner.sign(DefaultSigner.java:25)
	at com.alipay.api.AbstractAlipayClient.getRequestHolderWithSign(AbstractAlipayClient.java:855)
	at com.alipay.api.AbstractAlipayClient.doPost(AbstractAlipayClient.java:1000)
	at com.alipay.api.AbstractAlipayClient._execute(AbstractAlipayClient.java:940)
	at com.alipay.api.AbstractAlipayClient.execute(AbstractAlipayClient.java:415)
	at com.alipay.api.AbstractAlipayClient.execute(AbstractAlipayClient.java:397)
	at com.alipay.api.AbstractAlipayClient.execute(AbstractAlipayClient.java:392)
	at com.alipay.api.AbstractAlipayClient.execute(AbstractAlipayClient.java:386)
	at com.jyt.onepay.core.channel.unionpay.ali.UnionAlAsPayChannel.should_return_success_when_request_and_response_sm2(UnionAlAsPayChannel.java:82)
	at com.jyt.onepay.core.channel.unionpay.ali.UnionAlAsPayChannel.main(UnionAlAsPayChannel.java:90)
Caused by: com.alipay.api.AlipayApiException: SM2签名遭遇异常，请检查私钥格式是否正确。null content=alipay_sdk=alipay-sdk-java-dynamicVersionNo&app_id=2021000146614327&charset=utf-8&format=json&method=alipay.open.operation.openbizmock.biz.query&sign_type=SM2&timestamp=2020-04-13 09:44:49&version=1.0，charset=utf-8，privateKeySize=184
	at com.alipay.api.internal.util.asymmetric.BaseAsymmetricEncryptor.sign(BaseAsymmetricEncryptor.java:77)
	at com.alipay.api.internal.util.AlipaySignature.rsaSign(AlipaySignature.java:422)
	at com.alipay.api.DefaultSigner.sign(DefaultSigner.java:23)
	... 9 more

**Comment by zxx12138going** [comment]
因为4.9.106.ALL依赖的其他两个jar包，不是对应的版本，导致报错
